version: '3.8'

services:
  app:
    build: .
    container_name: eazipay-wallet-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4004:4004"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    container_name: eazipay-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: eazipay-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  mongo-data:
  redis-data: